// AUTO-GENERATED by `parton add magento http://localhost:5181`. Re-run `parton update magento` to refresh.
// parton:remote name=magento origin=http://localhost:5181

import { remote } from "@parton/framework"
import type { PaymentCap } from "./types.ts"

// `MAGENTO_REMOTE_ORIGIN` lets a test harness (or a worktree with
// remapped ports) point these bindings at a differently-addressed
// instance of the same remote without regenerating the file. The
// env var name derives from the install name (`magento`).
const ORIGIN = process.env.MAGENTO_REMOTE_ORIGIN ?? "http://localhost:5181"
const NAMESPACE = "magento"

export const CartSummary = remote({
  origin: ORIGIN,
  selector: "cart-summary",
  namespace: NAMESPACE,
})

export const MagentoCheckoutStep = remote({
  origin: ORIGIN,
  selector: "magento-checkout-step",
  namespace: NAMESPACE,
})

export const MagentoGreeting = remote({
  origin: ORIGIN,
  selector: "magento-greeting",
  namespace: NAMESPACE,
})

export const MagentoPaymentSummary = remote<PaymentCap>({
  origin: ORIGIN,
  selector: "magento-payment-summary",
  namespace: NAMESPACE,
})

export const MagentoStocks = remote({
  origin: ORIGIN,
  selector: "magento-stocks",
  namespace: NAMESPACE,
})
